med/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('medexpert/', include('medexpert.urls')),
    path('medics/', include('medics.urls')),
]

medexpert/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

app_name = 'medexpert'
urlpatterns = [
                  path('', auth_views.LoginView.as_view(template_name='medexpert/login.html'), name='login'),
                  path('register/', views.Register, name='register'),
                  path('home', views.home, name='home'),
                  path('update/', views.updateview, name='updateview'),
                  path('hospitals', views.view_hospital, name='view_hospital'),
                  path('firstaid', views.view_firstaid, name='view_firstaid'),
                  path('emergency', views.submit, name='submit'),
                  path('maps', views.view_maps, name='view_maps'),
                  path('message', views.send, name='send'),

                  path('register/', views.Register, name='register'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medics/urls.py
from django.urls import path
from medics import views
from django.conf import settings
from medics import views as user_views

from django.conf.urls.static import static

app_name='medics'
urlpatterns = [
      path('',views.home, name='home'),
      path('emergency',views.viewemergency,name= 'viewemergency'),
      path('message', views.viewmessage, name='viewmessage'),


]

medics/models.py
from django.db import models
from django.apps import AppConfig

class Account(models.Model):
    profile=models.ImageField()
    Username=models.CharField(max_length=50)
    website=models.URLField(max_length=60)
    email=models.EmailField(max_length=20)
    # help_and_feedback=models.URLField()



medics/forms.py
from django import forms
from medexpert.models import Msgs

class Tableform(forms.ModelForm):

    class Meta:
        model = Msgs
        fields='__all__'

medics/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.shortcuts import render, HttpResponse
from medexpert.models import Msgs
from medexpert.models import Emergency
from medics.forms import Tableform
from django.contrib import messages



def viewmessage(request):
    users =Msgs.objects.all()
    args ={'users':users}
    return render(request, 'medics/message.html', args)



def viewemergency(request):
    users =Emergency.objects.all()
    args ={'users':users}
    return render(request, 'medics/emergency.html', args)


def home(request):
    return render(request,'medics/index.html')

medics/templates/base3.html
{% load static %}


{% block body %}
<head>
	<meta charset="utf-8">
	<meta name="Viewport"
	content="width=device-width,initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible"
	content="ie=edge">
	  <link rel="stylesheet" type="text/css" href="{% static 'medics/css/style.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'medics/css/style.css' %}">

	<title>medics</title>
</head>

<body class="container full-height-grow">
		
<header class="main-header">
	<a href="/"class="brand-logo">

		<img src="{% static 'medics/images/logo.jpg' %} "height=50px>
		<div class="brand-logo-name">MEDICS</div>
	</a>
	<nav class="main-nav">

		<ul><br>
			<li><a href="discover.html">Discover</a></li>
			<li><a href="join.html">Join us</a></li>
			<li><a href="{% url 'medics:home' %}">HOME</a> </li>
            <li><a href="{% url 'medexpert:updateview"> NEWSUPDATE</a></li>
            <li><a href="{% url 'medics:viewemergency' %}">EMERGENCY</a> </li>

            <li><a href="{% url 'medics:viewmessage' %}">MESSAGES</a> </li>

            <li><a href="#">NOTIFICATION</a></li>
            <li><a href="#">ACCOUNT</a> </li>
		</ul>
	</nav>

</header>

<section class="home-main-section">
	<div class="img-wrapper">
		<div class="lady-image">
			
		</div>
		<div>
			<h1 class="Litte">Health is wealth </h1>
			<span class="subtite">"It is health that is real wealth and not pieces of gold and silver.” Mahatma Gandhi
			</span>
			<p><br>
			</p></div></div></section>




</body>
{% endblock %}