med/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('medexpert/', include('medexpert.urls')),
    path('medics/', include('medics.urls')),
]

medexpert/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

app_name = 'medexpert'
urlpatterns = [
                  path('', auth_views.LoginView.as_view(template_name='medexpert/login.html'), name='login'),
                  path('register/', views.Register, name='register'),
                  path('home', views.home, name='home'),
                  path('update/', views.updateview, name='updateview'),
                  path('hospitals', views.view_hospital, name='view_hospital'),
                  path('firstaid', views.view_firstaid, name='view_firstaid'),
                  path('emergency', views.submit, name='submit'),
                  path('maps', views.view_maps, name='view_maps'),
                  path('message', views.send, name='send'),

                  path('register/', views.Register, name='register'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medexpert/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
import time
from django.contrib.auth.models import User


class Emergency(models.Model):
    name = models.CharField(max_length=30)

    phone = models.IntegerField(default=0)
    email = models.EmailField(max_length=30)
    Type_Of_Emergency = models.CharField(max_length=500)
    Exact_Location = models.CharField(max_length=100)
    Time_submitted = models.DateTimeField(auto_now_add=True)


class Updates(models.Model):
    update_text = models.CharField(max_length=1000)
    pub_date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='media', blank=True)
    video = models.FileField(upload_to='media', blank=True)


class Home(models.Model):
    content = models.TextField()


class Hospitals(models.Model):
    hospital_name = models.CharField(max_length=100)
    phone = models.IntegerField(default=0)
    email = models.EmailField(max_length=30)
    services = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    website = models.URLField()
    image = models.ImageField(upload_to='media', blank=True)
    hometown = models.CharField(max_length=100)


class FirstAid(models.Model):
    description = models.CharField(max_length=1000)
    image = models.ImageField(upload_to='media', blank=True)


class Map(models.Model):
    Area = models.CharField(max_length=1000)


#
# class Registration2(models.Model):
#
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     mobile=models.IntegerField(default=0)
#     email=models.EmailField(blank=True)
#     physical_address=models.CharField(max_length=100, blank=True)
#     home_town=models.CharField(max_length=50)
#     date_of_birth=models.DateField(default=time.timezone)
#     gender= models.CharField(max_length=20,blank=True)
#     pic = models.ImageField(upload_to='media', blank=True)
#     #
#     # @receiver(post_save,sender=User)
#     # def addons(sender,instance, created, **kwargs):
#     #     if created:
#     #         Registration2.objects.create(user=instance)
#     #     instance.registration2.save()


class Msgs(models.Model):
    name = models.CharField(max_length=25)
    phone = models.IntegerField()
    Email = models.EmailField(max_length=40)
    Subject = models.TextField(max_length=20)
    message = models.TextField(max_length=500)
    time_sent = models.DateTimeField(auto_now_add=True)


# Login and Reg models


class Profile(models.Model):
    gender_choices = (
        ('M', 'Male'),
        ('F', 'Female')
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phonenumber = models.IntegerField()
    dateofbirth = models.DateField(max_length=30)
    gender = models.CharField(choices=gender_choices,max_length=7)

    def __str__(self):
        return self.user.username

medexpert/forms.py
from django import forms
from .models import Emergency
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class Table(forms.ModelForm):
    class Meta:
        model = Emergency
        fields = '__all__'


class Reg(UserCreationForm):
    gender_choices = (
        ('M', 'Male'),
        ('F', 'Female')
    )
    phonenumber = forms.CharField(widget=forms.NumberInput(attrs={'type': 'number', 'class': 'form-control'}))
    dateofbirth = forms.CharField(widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}))
    gender = forms.ChoiceField(choices=gender_choices,widget=forms.RadioSelect())
    email = forms.CharField(widget=forms.EmailInput(attrs={'type': 'email', 'class': 'form-control'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'type': 'text', 'class': 'form-control'}))
    username=forms.CharField(widget=forms.TextInput(attrs={'type': 'text', 'class': 'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'type': 'text', 'class': 'form-control'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'type': 'password', 'class': 'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'type': 'password', 'class': 'form-control'}))


    class Meta:
        model = User
        fields = ('first_name','last_name','username', 'email','phonenumber','gender', 'dateofbirth')
'''
pno
email
date of birth
gender
pass
fname
lname
'''

medexpert/views.py
from django.shortcuts import render, get_list_or_404, redirect
from .models import Updates
from django.http import HttpResponse
from django.contrib.auth.models import User
from .models import Hospitals,Map
from .models import FirstAid,Emergency,Profile
from .forms import Table,Reg
from medics.forms import Tableform
from django.contrib.auth import authenticate, get_user_model, login, logout



def submit(request):
    if request.method == 'POST':
        form = Table(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse('Data saved in the resipitory')

    else:
        form = Table()
        args = {'form': form}
        return render(request, 'medexpert/emergency.html', args)


def home(request):
    return render(request,"medexpert/home.html")



def updateview(request):
    latest_updates=get_list_or_404(Updates)
    print(latest_updates)
    context= {'latest_updates': latest_updates }
    return render(request,'medexpert/index.html',context)





def view_hospital(request):
    nearby_hospitals=get_list_or_404(Hospitals)
    print(nearby_hospitals)
    arg= {'nearby_hospitals':  nearby_hospitals }
    return render(request, 'medexpert/hospitals.html', arg)


def view_firstaid(request):
    firstaid_operations=get_list_or_404(FirstAid)
    print(firstaid_operations)
    cnxt= {'firstaid_operations':  firstaid_operations }
    return render(request, 'medexpert/firstaid.html', cnxt)


def view_maps(request):
    # location=get_list_or_404(Map)
    # print(location)
    # cnxt= {'location':  location }
    return render(request, 'medexpert/maps.html')


def Register(request):
    if request.method == 'POST':
        form = Reg(request.POST)
        if form.is_valid():
            form.save()
            return redirect('medexpert:login')

    else:
        form = Reg()
    args = {'form': form}
    return render(request, 'medexpert/register.html', args)


#########################################################################
# def login(request):
#     if request.method =='POST':
#         Data=Profile(username=request.POST['username'],
#                   password=request.POST['password'])
#         Data.save()
#         return render(request,'medexpert/home.html')
#     else:
#         return render(request,'medexpert/login.html')

###########################################################################

def send(request):
    if request.method == 'POST':
        form = Tableform(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'medexpert/message.html')


    else:
        form = Tableform()
    args = {'form':form}
    return render(request, 'medexpert/message.html', args)






medexpert/templates/medexpert/banner.html
<!DOCTYPE html>
<html lang="en">
 <!--banner-->
  <section id="banner" class="banner">
    <div class="bg-color">
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="col-md-12">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
				      </button>
              <a class="navbar-brand" href="#"><img src="img/logo.png" class="img-responsive" style="width: 140px; margin-top: -16px;"></a>
            </div>
            <div class="collapse navbar-collapse navbar-right" id="myNavbar">
              <ul class="nav navbar-nav">
                <li class="active"><a href="#banner">Home</a></li>
                <li class=""><a href="#service">Services</a></li>
                <li class=""><a href="#about">About</a></li>
                <li class=""><a href="#testimonial">Testimonial</a></li>
                <li class=""><a href="#contact">Contact</a></li>
              </ul>
            </div>
          </div>
        </div>
      </nav>
      <div class="container">
        <div class="row">
          <div class="banner-info">
            <div class="banner-logo text-center">
              <img src="img/logo.png" class="img-responsive">
            </div>
            <div class="banner-text text-center">
              <h1 class="white">Healthcare at your desk!!</h1>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod <br>tempor incididunt ut labore et dolore magna aliqua.</p>
              <a href="#contact" class="btn btn-appoint">Make an Appointment.</a>
            </div>
            <div class="overlay-detail text-center">
              <a href="#service"><i class="fa fa-angle-down"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--/ banner-->
<body>

</body>
</html>

medexpert/templates/medexpert/clinics.html
{% extends 'base.html' %}
{% block body %}

<head>
    <meta charset="UTF-8">
    <title>CLINICS</title>
</head>
<body>

<div class='w3-card-2 topnav' id='topnav'>
  <div style="overflow:auto;">


      <nav class="navbar navbar-expand-lg navbar-light bg-light">
<ul><h3>

      <a href='javascript:void(0);' class='topnav-icons fa fa-menu w3-hide-large w3-left w3-bar-item w3-button' onclick='open_menu()' title='Menu'></a>
      <a href='../default.html' class='topnav-icons fa fa-home w3-left w3-bar-item w3-button' title='Home'></a>

    <a class="w3-bar-item w3-button" href='' title='Medexpert'>NEARBY CLINICS </a>

    <a class="w3-bar-item w3-button" href='' title='Medexpert'>MAPS</a>
</h3></ul>
</nav></div> </div>


{% for clinics in clinics_nearby %}


{{clinics.hospital_name}}
{{clinics.phone}}
{{clinics.email}}
{{clinics.services}}
{{clinics.description}}
{{clinics.city}}
{{clinics.website}}
{{clinics.image}}
<img src ='{{ clinics.image.url }}'>

{{clinics.hometown }}

</body>
{% endfor %}
{% endblock %}


medexpert/templates/medexpert/contact.html
<!DOCTYPE html>
<html lang="en">
<!--contact-->
  <section id="contact" class="section-padding">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="ser-title">Contact us</h2>
          <hr class="botm-line">
        </div>
        <div class="col-md-4 col-sm-4">
          <h3>Contact Info</h3>
          <div class="space"></div>
          <p><i class="fa fa-map-marker fa-fw pull-left fa-2x"></i>321 Tom Mboya Street<br> Nairobi, 17022</p>
          <div class="space"></div>
          <p><i class="fa fa-envelope-o fa-fw pull-left fa-2x"></i>info@medexpert.com</p>
          <div class="space"></div>
          <p><i class="fa fa-phone fa-fw pull-left fa-2x"></i>+254 700 123 1234</p>
        </div>
      </div>
    </div>
  </section>

<body>

</body>
</html>

medexpert/templates/medexpert/cta.html
<!DOCTYPE html>
<html lang="en">
<!--cta-->
  <section id="cta-1" class="section-padding">
    <div class="container">
      <div class="row">
        <div class="schedule-tab">
          <div class="col-md-4 col-sm-4 bor-left">
            <div class="mt-boxy-color"></div>
            <div class="medi-info">
              <h3>Emergency Case</h3>
              <p>I am text block. Edit this text from Appearance / Customize / Homepage header columns. Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
              <a href="#" class="medi-info-btn">READ MORE</a>
            </div>
          </div>
          <div class="col-md-4 col-sm-4">
            <div class="medi-info">
              <h3>Emergency Case</h3>
              <p>I am text block. Edit this text from Appearance / Customize / Homepage header columns. Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
              <a href="#" class="medi-info-btn">READ MORE</a>
            </div>
          </div>
          <div class="col-md-4 col-sm-4 mt-boxy-3">
            <div class="mt-boxy-color"></div>
            <div class="time-info">
              <h3>Opening Hours</h3>
              <table style="margin: 8px 0px 0px;" border="1">
                <tbody>
                  <tr>
                    <td>Monday - Friday</td>
                    <td>8.00 - 17.00</td>
                  </tr>
                  <tr>
                    <td>Saturday</td>
                    <td>9.30 - 17.30</td>
                  </tr>
                  <tr>
                    <td>Sunday</td>
                    <td>9.30 - 15.00</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--cta-->


<body>

</body>
</html>

medexpert/templates/medexpert/doctorteam.html
{% load static %}
<html>
<html lang="en">
 <!--doctor team-->
  <section id="doctor-team" class="section-padding">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="ser-title">Meet Our Specialised Doctors!</h2>
          <hr class="botm-line">
        </div>
        <div class="col-md-3 col-sm-3 col-xs-6">
          <div class="thumbnail">
                        <img src="{% static 'medexpert/img/doctor1.jpg' %}" alt="..." class="team-img">

            <div class="caption">
              <h3>Jessica Wally</h3>
              <p>Physiciarist</p>
              <ul class="list-inline">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-3 col-xs-6">
          <div class="thumbnail">
                        <img src="{% static 'medexpert/img/doctor2.jpg' %}" alt="..." class="team-img">

            <div class="caption">
              <h3>Iai Donas</h3>
              <p>Neuro-sergion</p>
              <ul class="list-inline">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-3 col-xs-6">
          <div class="thumbnail">
                        <img src="{% static 'medexpert/img/doctor3.jpg' %}" alt="..." class="team-img">

            <div class="caption">
              <h3>Amanda Denyl</h3>
              <p>Psycologist</p>
              <ul class="list-inline">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-3 col-xs-6">
          <div class="thumbnail">
            <img src="{% static 'medexpert/img/doctor4.jpg' %}" alt="..." class="team-img">
            <div class="caption">
              <h3>Jason Davis</h3>
              <p>Doctor</p>
              <ul class="list-inline">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--/ doctor team-->
<body>

</body>
</html>

medexpert/templates/medexpert/firstaid.html
{% extends 'base.html' %}
{% block body %}
{% load static %}
<body>

<div class='w3-card-2 topnav' id='topnav'>
  <div style="overflow:auto;">
  </div>
</div>
</div>
</body>
<p style="background-color:powderblue;"/>
<h1>FIRST AID</h1>
{% for firstaid in  firstaid_operations %}
				<video autoplay loop muted playsinline src="{% static 'medexpert/img/firstaid.mp4' %}" width="1000" height="500"></video>

{{firstaid.description}}
{{firstaid.image}}
<img src ='{{ hospitals.image.url }}'>


    <div class="container">
      <div class="row">

        <div class="col-md-2 col-sm-2 col-xs-6">
          <div class="thumbnail">

            <div class="caption">

<iframe width="220" height="115"
src="https://www.youtube.com/embed/tgbNymZ7vqY">
</iframe>

              </ul>
            </div>
          </div>
        </div>

        <div class="col-md-2 col-sm-2 col-xs-6">
          <div class="thumbnail">

            <div class="caption">

<iframe width="220" height="115"
src="https://www.youtube.com/watch?v=Ef5wRT11dNI">
</iframe>
            </div>
          </div>
        </div>

      </div>
    </div>
</section>


<div class="main">
<section id="doctor-team" class="section-padding">
    <div class="container">
      <div class="row">

        <div class="col-md-2 col-sm-2 col-xs-4">
          <div class="thumbnail">

            <div class="caption">
              <h3>TROPICAL DISEASES</h3>
              <p>tropical diseases in the world</p>
              <ul class="list-inline">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
              </ul>
            </div>
          </div>
        </div>

        <div class="col-md-2 col-sm-2 col-xs-4">
          <div class="thumbnail">

            <div class="caption">
              <h3>TROPICAL DISEASES</h3>
              <p>tropical diseases in the world</p>
              <ul class="list-inline">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
              </ul>
            </div>
          </div>
        </div>

        <div class="col-md-2 col-sm-2 col-xs-4">
          <div class="thumbnail">

            <div class="caption">
              <h3>TROPICAL DISEASES</h3>
              <p>tropical diseases in the world</p>
              <ul class="list-inline">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
              </ul>
            </div>
          </div>
        </div>

        <div class="col-md-2 col-sm-2 col-xs-4">
          <div class="thumbnail">

            <div class="caption">
              <h3>TROPICAL DISEASES</h3>
              <p>tropical diseases in the world</p>
              <ul class="list-inline">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
              </ul>
            </div>
          </div>
        </div>

        <div class="col-md-2 col-sm-2 col-xs-4">
          <div class="thumbnail">

            <div class="caption">
              <h3>TROPICAL DISEASES</h3>
              <p>tropical diseases in the world</p>
              <ul class="list-inline">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-2 col-sm-2 col-xs-4">
          <div class="thumbnail">

            <div class="caption">
              <h3>Major diseases in the world</h3>
              <p>HIV/AIDS and TUBERCULOSIS</p>
              <ul class="list-inline">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
              </ul>
            </div>

          </div>
        </div>
      </div>
    </div>
</section>
</div>

{% endfor %}

{% endblock %}




medexpert/templates/medexpert/footer.html
<!DOCTYPE html>
<html lang="en">
<!--footer-->
  <footer id="footer">
    <div class="top-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-4 col-sm-4 marb20">
            <div class="ftr-tle">
              <h4 class="white no-padding">About Us</h4>
            </div>
            <div class="info-sec">
              <p>Praesent convallis tortor et enim laoreet, vel consectetur purus latoque penatibus et dis parturient.</p>
            </div>
          </div>
          <div class="col-md-4 col-sm-4 marb20">
            <div class="ftr-tle">
              <h4 class="white no-padding">Quick Links</h4>
            </div>
            <div class="info-sec">
              <ul class="quick-info">
                <li><a href="#"><i class="fa fa-circle"></i>Home</a></li>
                <li><a href="#service"><i class="fa fa-circle"></i>Service</a></li>
                <li><a href="#contact"><i class="fa fa-circle"></i>Appointment</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4 col-sm-4 marb20">
            <div class="ftr-tle">
              <h4 class="white no-padding">Follow us</h4>
            </div>
            <div class="info-sec">
              <ul class="social-icon">
                <li class="bglight-blue"><i class="fa fa-facebook"></i></li>
                <li class="bgred"><i class="fa fa-google-plus"></i></li>
                <li class="bgdark-blue"><i class="fa fa-linkedin"></i></li>
                <li class="bglight-blue"><i class="fa fa-twitter"></i></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="footer-line">
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-center">
            © Copyright Medexpert!!!. All Rights Reserved
            <div class="credits">

              Designed by <b><i>Peter Rogendo</i></b>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!--/ footer-->

<body>

</body>
</html>

medexpert/templates/medexpert/home.html
{% extends 'base.html' %}
{% block body %}


{% include 'medexpert/sevices.html' %}
{% include 'medexpert/cta.html' %}
{% include 'medexpert/about.html' %}
{% include 'medexpert/doctorteam.html' %}
{% include 'medexpert/testimonial.html' %}
{% include 'medexpert/cta2.html' %}
{% include 'medexpert/contact.html' %}
{% include 'medexpert/footer.html' %}
{% endblock %}

medexpert/templates/medexpert/login.html
{% extends 'base2.html' %}
{% load static %}
{% block body %}


</head>

    <div class="col-md-2">
        <a href="{% url 'medexpert:register' %}">
            SignUp</a>
    </div>
<form method="post">
{% csrf_token %}
    <div class="col-md-8">
        <div class="form-group">
            <div class="form-group">
                <label for="username">Username
                </label>
                <input type="text" name="username" class="form-control" required />
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" name="password" required />
            </div>
            <label class="text-danger" style="position: center">{{ msg }}</label>
            <br />
            <div class="form-group">
                <button class="btn btn-primary form-control"><span class="glyphicon-log-in"></span>Login </button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

medexpert/templates/medexpert/message.html

{% load static %}
<html>
<html lang="en">
<head>
    <meta charset="UTF-8">

      <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans|Raleway|Candal">
  <link rel="stylesheet" type="text/css" href="{% static 'medexpert/css/font-awesome.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'medexpert/css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'medexpert/css/style.css' %}">
  <script src="{% static 'medexpert/js/jquery.js' %}"></script>
  <script src="{% static 'medexpert/js/bootstrap.min.js' %}"></script>

            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
				      </button>

 <a class="navbar-brand" href="#"><img src="{% static 'medexpert/img/logo.png' %}" class="img-responsive" style="width: 140px; margin-top: -16px;"></a>
            </div>
            <div class="collapse navbar-collapse navbar-right" id="myNavbar"></div><li style="color:red;">
              <ul class="nav navbar-nav">




                <li><a href="{% url 'medexpert:home' %}"><i class="fa fa-home" style="font-size:48px;color:black"></i>HOME</a> </li>
                  <li><a href="{% url 'medexpert:updateview' %}"><i class="fa fa-newspaper-o" style="font-size:48px;color:wheat"></i> NEWSUPDATE</a></li>
                  <li><a href="{% url 'medexpert:submit' %}"><i class="fa fa-ambulance" style="font-size:48px;color:red"></i>EMERGENCY</a> </li>

                <li><a href="{% url 'medexpert:view_hospital' %}"><i class="fa fa-hospital-o" style="font-size:48px;color:red"></i>
HOSPITALS</a> </li>

                  <li><a href="{% url 'medexpert:view_maps' %}"><i class="fa fa-map-o" style="font-size:48px;color:green"></i>

MAP</a></li>
                <li><a href="{% url 'medexpert:view_firstaid' %}"><i class="fa fa-medkit" style="font-size:48px;color:red"></i>FIRST-AID</a> </li>

<style>
.dropdown {
  position: relative;
  display: block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #a0f9e8;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(107, 146, 252, 0.75);
  padding: 12px 16px;
  z-index: 1;
}

.dropdown:hover .dropdown-content {
  display: block;
}

</style>
<li>
<div class="dropdown">

    <i class="fa fa-bars" style="font-size:48px;color:black"></i>
  <div class="dropdown-content">
      <a href="{% url 'medexpert:send' %}"><i class="fa fa-bookmark"></i>APPOINTMENT</a><br><br>
          <a href="#"><i class="fa fa-bell"></i>NOTIFICATION</a><br><br>
                <a href="#"><i class="fa fa-question-circle"></i>HELP</a>


  </div>
</div>
              </ul></li><br><br><br><br><br><br>

    <title>message</title>
</head>

<body>
<h4><b><i>BOOK AN APPOINTMENT or MAKE ENQUIRES</i></b></h4>


<br><br><br><br><br><form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">submit</button>
    <button><a href="{% url 'medexpert:home' %}">Go Back</a></button>

</form>
<br><br><br><br><br><br>



</body>
{% include 'medexpert/footer.html' %}
</html>
